<?php
/*
    Copyright (C) 2012 John Hamer <J.Hamer@cs.auckland.ac.nz>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

//- This is a PROTOTYPE (AWS) Aropa configuration file.  If you need to make changes,
//- copy this to local-config.php and edit to match your local environment.
//- DO NOT EDIT THIS FILE

define("AROPA_SESSION_NAME", "AROPA-PHP-SESSION");

//------------------
//- Error logging
//------------------

//- What to do with error messages.  Options are:
//-      'email' -- email the administrator (requires ADMIN_EMAIL and SMTP)
//-      'log'   -- write to ./LOGFILE
//-      'debug' -- display fleetingly in the debug pane.  Of interest
//-                 to developers only.

define("ADMIN_EMAIL", 'YOUR-CONTACT-EMAIL' );
ini_set('SMTP', 'YOUR-SMTP-SERVER');

define("LOG_ERRORS", 'log' );
//define("LOG_ERRORS", 'log' );
//define("LOG_ERRORS", 'debug' );

// Set to true to have all queries written to QUERY-TRACE.sql
//define('ARE_DEBUGGING', 'false' );


//------------------------------
//- MySQL database connection
//------------------------------

//- The following are essential connection details for the MySQL
//- database.  Before using Aropa, the database tables should be created
//- by 'source'ing the tables.sql script.

//- The HOST is the IP address of the database server.  If the server
//- listens on a non-standard port, then use the syntax "hostname:port"
define("AROPA_DB_HOST", $_SERVER['DB_HOST']);
if (empty($_SERVER['DB_PORT']))
  define("AROPA_DB_PORT", '3306');
else
  define("AROPA_DB_PORT", $_SERVER['DB_PORT']);

//- A MySQL user and password.  This should be a restricted user, with
//- SELECT, INSERT, UPDATE, DELETE
//- privileges only.  E.g., on the MySQL server, run
//-   GRANT SELECT, INSERT, UPDATE, DELETE
//           ON aropa.* TO 'aropa'@'www server IP address';
//- where 'www server IP address' is the IP address of the web server
//- that runs the Aropa system.

//- The password should be set on the MySQL server using
//-   SET PASSWORD FOR aropa = PASSWORD('SECRET PASSWORD');
//- You can use the mkPasswd.php utility to generate a random password.

define("AROPA_DB_USER", $_SERVER['DB_USERNAME']);
define("AROPA_DB_PASSWORD", $_SERVER['DB_PASSWORD']);

//- The MySQL database to use (i.e., the database selected at the time
//- you 'source'd tables.sql)
define("AROPA_DB_DATABASE", $_SERVER['DB_DATABASE']);


//- Set USE_DATABASE_SESSION to true if you want session data to be
//- stored in the Aropa database, thus making it possible for
//- administrators to see who is currently logged in.  Some versions of
//- PHP (e.g., 4.3.x) appear to have problems with this (see
//- http://bugs.php.net/bug.php?id=21306).  You will know if your PHP
//- version is affected from the appearance of the message "Unknown(): A
//- session is active. You cannot change the session module's ini
//- settings at this time. in Unknown on line 0", together with an
//- inability to log in.
define('USE_DATABASE_SESSION', true );

if( function_exists( 'date_default_timezone_set' ) )
  date_default_timezone_set( 'Pacific/Auckland' );
